# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"cs-cz\">

    <head>
        <meta charset=\"utf-8\" /> 
        <link href=\"static/style.css\" rel=\"stylesheet\">
        <script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>
        <script src=\"static/WifiManager.js\"></script>
        <script src=\"static/func.js\"></script> 
        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js\" type=\"text/javascript\"></script>
        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>
        
        <title>Olife Energy</title>
    </head>
 
    <body>
        <header>
            <div id=\"logo\"></div>
            <nav>
                <ul class=\"menu\">
                    <li id=\"main\" class=\"aktivni\"><a class=\"aktiv\" >Přehled</a></li>
                    <li id=\"settings\"><a >Nastavení</a></li>
                    <li id=\"contact\"><a >Kontakt</a></li>
                </ul>
            </nav>
    </header>
    
        <article>
            <section>
                <div class=\"mainContainer\">
                </div>
                
            </section>
            <div class=\"cistic\"></div>
    
        </article>
        
        
    </body>
</html>"""
