# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"cs-cz\">
<table id=\"tableData\">
    <thead>
        <tr><th>Name</th><th>Status/Value</th><th>Unit</th></tr>
    </thead>   
    <tbody> 
        <tr><td>Time:</td><td><span id=\"time\">0</span></td><td><span> </span></td></tr>
        <tr><td>U1 value:</td><td><span id=\"U1\">0</span></td><td><span> V</span></td></tr>
        <tr><td>U2 value:</td><td><span id=\"U2\">0</span></td><td><span> V</span></td></tr>
        <tr><td>U3 value:</td><td><span id=\"U3\">0</span></td><td><span> V</span></td></tr>
        <tr><td>I1 value:</td><td><span id=\"I1\">0</span></td><td><span> mA</span></td></tr>
        <tr><td>I2 value:</td><td><span id=\"I2\">0</span></td><td><span> mA</span></td></tr>
        <tr><td>I3 value:</td><td><span id=\"I3\">0</span></td><td><span> mA</span></td></tr>
        <tr><td>P1 value:</td><td><span id=\"P1\">0</span></td><td><span> W</span></td></tr>
        <tr><td>P2 value:</td><td><span id=\"P2\">0</span></td><td><span> W</span></td></tr>
        <tr><td>P3 value:</td><td><span id=\"P3\">0</span></td><td><span> W</span></td></tr>
        <tr><td>E1 value:</td><td><span id=\"E1\">0</span></td><td><span> kWh</span></td></tr>
        <tr><td>E2 value:</td><td><span id=\"E2\">0</span></td><td><span> kWh</span></td></tr>
        <tr><td>E3 value:</td><td><span id=\"E3\">0</span></td><td><span> kWh</span></td></tr>
    </tbody> 
</table>  
 

        <canvas id=\"powerGraph\">
            <p>Your browser does not support the canvas element.</p>
        </canvas>

        <canvas id=\"energyGraph\">
            <p>Your browser does not support the canvas element.</p>
        </canvas>

</html>
                     """
