# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html><div class=\"container-sm text-center\"><span class=\"dim\">HOURLY ENERGY</span><canvas id=\"energyGraph_hourly\" class=\"g\"><p>Does not support</p></canvas><div class=\"mt-4\"><span class=\"dim\">DAILY ENERGY</span></div><canvas id=\"energyGraph_daily\" class=\"g\"><p>Does not support</p></canvas></div>"""
