# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"cs-cz\">
 
    <head> 
           
        <title>Wattmeter</title>
        
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
         <link href=\"main/static/style.css\" rel=\"stylesheet\">
         <script type=\"text/javascript\" src=\"main/static/cached-webpgr.js\"></script>
        <script type=\"text/javascript\" src=\"main/static/loadLibrary.js\"></script>

    
    </head> 
   
    <body onload=\"loadLibrary()\">

        <nav> 
            <ul class=\"menu\">
                <li><a id=\"main\" class=\"active\" >OVERVIEW</a></li>
                <li><a id=\"settings\">SETTINGS</a></li>
             </ul>
        </nav>
        
        <h2 class=\"loading\">Loading</h2>

                <div class=\"mainContainer\"></div>

    </body>
    
</html>
"""
