# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"cs-cz\">
 
    <head>
        <meta name=\"viewport\" content=\"width=device-width\">
        <meta charset=\"utf-8\" />
        
        <link href=\"static/style.css\" rel=\"stylesheet\">
        <script src=\"static/jquery-3.4.1.min.js\"></script>
        <script src=\"static/WifiManager.js\"></script>
        <script src=\"static/func.js\"></script> 
        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js\" type=\"text/javascript\"></script>
          
        <title>Olife Energy</title>
    </head>
  
    <body>
           <nav>
                <ul class=\"menu\">
                    <li><a id=\"main\" class=\"active\" >Přehled</a></li>
                    <li><a id=\"settings\">Nastavení</a></li>
                    <li><a id=\"contact\" >Kontakt</a></li>
                </ul>
            </nav>
                <div class=\"mainContainer\">
                </div>
                
            
    
        
    </body>
</html>"""
