# Autogenerated file
def render(*a, **d):
    yield """<div class=\"container-sm text-center mt-3 mb-3 bg-dark\"> <div class=\"btn-group btn-group-toggle\" data-toggle=buttons > <label class=\"btn btn-dark btn-lg active\"> <input type=radio  name=options  checked> Last hour </label> </div> <div class=\"container-sm mt-3\"> <canvas id=powerGraph  class=g ></canvas> </div> </div>"""
