# Autogenerated file
def render(*a, **d):
    yield """<div class=\"container-sm text-center mt-3 mb-3\" style=\"background:#000;\"> <h3 style=\"color: #34ECE1; font-weight: bold;\" data-i18n-key=lastHour >Last hour</h3> </div> <div class=\"container-sm mt-3\"> <canvas id=powerGraph  class=g ></canvas> </div> </div>"""
