# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html>
<div class=\"container-sm text-white mt-2\">
    <div class=\"container-fluid bg-primary pt-2 text-center\">
        <h3>Wi-Fi Client Setup</h3>
    </div>
    <div class=\"container -fluid  text-white\">  
        <table class=\"table table-borderless text-center  text-white\">
            <tbody>
                <tr class=\"ssidTable\">
                    <td id=\"ssid\" colspan=\"2\"><td>
                </tr>        
                <tr> 
                    <td>Password:</td> 
                    <td><input id=\"passwordField\" name=\"password\" type=\"password\" /></td>
                </tr>
            </tbody>
        </table>

        <div class=\"container text-center  text-white\">    
            <div class=\"btn-group\">
                <button  id=\"setSSID\" type=\"button\" class=\"btn btn-primary\">submit</button>
                <button  id=\"refreshSSID\" type=\"button\" class=\"btn btn-primary \">refresh</button>
            </div>
        </div>
       <br>
    </div>
    <div class=\"container-fluid bg-primary pt-2 text-center\">
        <h3>Regulation setup</h3>
    </div>
    <div class=\"container text-center\" id=\"settingTable\">    
        <div class=\"row align-items-start\">
            <div class=\"col\">
                <h6>Info</h6>
            </div>
            <div class=\"col\">
                <h6>State</h6>
            </div>
        </div>      
    </div>
    
    
    <div class=\"container-fluid bg-primary pt-2 text-center\">
        <h3>Modbus interface</h3>
    </div>
    <div class=\"container-fluid  text-white\">  
        <table class=\"table table-borderless text-center  text-white\" > 
            <thead  >
                <tr>
                    <th style=\"width:60%;\">Register</th>
                    <th style=\"width:80%;\">Data</th>
                </tr>
            </thead>
            <tbody> 
                <tr> 
                    <td><input id=\"modbusReg\"  style=\"width:60%;\" name=\"number\" type=\"number\" /></td>
                    <td><input id=\"modbusIO\"   style=\"width:80%;\" name=\"text\" type=\"text\" /></td>
                </tr>
            </tbody>
        </table>

        <div class=\"container text-center  text-white\">    
            <div class=\"btn-group\">
                <button  id=\"readReg\" type=\"button\" class=\"btn btn-primary\">readReg</button>
            </div>
        </div>
       <br>
    </div>
    
    
</div> 
    

</html>"""
