# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html>
    <h1 style=\" text-align: center;\">
            Wi-Fi Client Setup
    </h1>
    <table style=\"margin-left: auto; margin-right: auto;\">
        <tr>
            <td colspan=\"2\"><div class=\"loader\"></div></td>
        </tr>
        <tr class=\"ssidTable\">
            <td id=\"ssid\" colspan=\"2\"></td>
        </tr>
        
        <tr>
            <td>Password:</td> 
            <td><input id=\"passwordField\" name=\"password\" type=\"password\" /></td>
        </tr>
    </tbody>
    </table>
    <div class=\"button\"  style =\"margin-left: 40%;\">
         <input id=\"setSSID\" type=\"submit\" value=\"submit\"/>
    </div>
    <div class=\"button\">
        <input id=\"refreshSSID\" type=\"submit\" value=\"refresh\"/>
    </div>
    <p>&nbsp;</p>

    <hr />
    
        <h1 style=\" text-align: center;\">
            Wattmeter Setup
    </h1>
    <table style=\"margin-left: auto; margin-right: auto;\">
        <tr>
            <td>reset Energy counter </td> 
            <td><input id=\"text\" name=\"text\" type=\"text\" /></td>
            <td><input id=\"resetEnergy\" type=\"submit\" value=\"set\"/></td>
        </tr>
    </tbody>
    </table>
    <p>&nbsp;</p>
    <hr />
</html>"""
